# QAttitude

Attitude representation and estimation.

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from QAttitude.rep.quaternion import Quaternion
from QAttitude.rep.euler import euler_to_quat, quat_to_euler
from QAttitude.plot import plot_attitude

## Attitude Representation - Quaternions

In [2]:
print("1. Identity Quaternion")
q_id = Quaternion.identity()
print("q_identity =", q_id)
print("norm =", q_id.norm())
print("\n")

print("2. Quaternion from Euler angles")
roll, pitch, yaw = 0.3, -0.2, 0.5  # radians
q_euler = euler_to_quat(roll, pitch, yaw)
print(f"Euler (r,p,y) = ({roll:.3f}, {pitch:.3f}, {yaw:.3f})")
print("Quaternion =", q_euler)
print("\n")

print("3. Quaternion → Euler conversion")
r, p, y = quat_to_euler(q_euler)
print(f"Recovered Euler (r,p,y) = ({r:.3f}, {p:.3f}, {y:.3f})")
print("\n")

print("4. Quaternion multiplication (composition)")
q1 = euler_to_quat(0.2, 0.0, 0.0)   # roll
q2 = euler_to_quat(0.0, 0.3, 0.0)   # pitch
q_comp = q1 * q2
print("q1 (roll)  =", q1)
print("q2 (pitch) =", q2)
print("q1 * q2    =", q_comp)
print("\n")

print("5. Quaternion conjugate and inverse")
print("q           =", q_comp)
print("conjugate   =", q_comp.conjugate())
print("inverse     =", q_comp.inverse())
print("q * q⁻¹     =", q_comp * q_comp.inverse())
print("\n")

1. Identity Quaternion
q_identity = Quaternion(w=1, x=0, y=0, z=0)
norm = 1.0


2. Quaternion from Euler angles
Euler (r,p,y) = (0.300, -0.200, 0.500)
Quaternion = Quaternion(w=0.949555, x=0.168491, y=-0.0588568, z=0.257859)


3. Quaternion → Euler conversion
Recovered Euler (r,p,y) = (0.300, -0.200, 0.500)


4. Quaternion multiplication (composition)
q1 (roll)  = Quaternion(w=0.995004, x=0.0998334, y=0, z=0)
q2 (pitch) = Quaternion(w=0.988771, x=0, y=0.149438, z=0)
q1 * q2    = Quaternion(w=0.983831, x=0.0987124, y=0.148692, z=0.0149189)


5. Quaternion conjugate and inverse
q           = Quaternion(w=0.983831, x=0.0987124, y=0.148692, z=0.0149189)
conjugate   = Quaternion(w=0.983831, x=-0.0987124, y=-0.148692, z=-0.0149189)
inverse     = Quaternion(w=0.983831, x=-0.0987124, y=-0.148692, z=-0.0149189)
q * q⁻¹     = Quaternion(w=1, x=0, y=-1.0842e-18, z=-1.73472e-18)




In [3]:
print("6. Rotate a vector")
v = np.array([1.0, 0.0, 0.0])
v_rot = q_euler.rotate(v)
print("Original vector =", v)
print("Rotated vector  =", v_rot)
print("\n")

print("7. Quaternion → Rotation Matrix")
R = q_euler.to_rotation_matrix()
print("Rotation matrix:\n", R)
print("\n")

print("8. Rotation Matrix → Quaternion")
q_from_R = Quaternion.from_rotation_matrix(R)
print("Recovered quaternion =", q_from_R)
print("Dot(q, q_from_R) =", q_euler.dot(q_from_R))
print("\n")

print("9. Canonical form (sign consistency)")
q_neg = Quaternion(-q_euler.w, -q_euler.x, -q_euler.y, -q_euler.z)
print("q      =", q_euler)
print("-q     =", q_neg)
print("canonical(-q) =", q_neg.canonical())
print("\n")

print("10. Quaternion array interface")
arr = q_euler.as_array()
print("as_array =", arr)
print("from_array =", Quaternion.from_array(arr))
print("\n")



6. Rotate a vector
Original vector = [1. 0. 0.]
Rotated vector  = [0.86008934 0.46986895 0.19866933]


7. Quaternion → Rotation Matrix
Rotation matrix:
 [[ 0.86008934 -0.50953629 -0.02488178]
 [ 0.46986895  0.81023919 -0.35033646]
 [ 0.19866933  0.28962948  0.93629336]]


8. Rotation Matrix → Quaternion
Recovered quaternion = Quaternion(w=0.949555, x=0.168491, y=-0.0588568, z=0.257859)
Dot(q, q_from_R) = 1.0


9. Canonical form (sign consistency)
q      = Quaternion(w=0.949555, x=0.168491, y=-0.0588568, z=0.257859)
-q     = Quaternion(w=-0.949555, x=-0.168491, y=0.0588568, z=-0.257859)
canonical(-q) = Quaternion(w=0.949555, x=0.168491, y=-0.0588568, z=0.257859)


10. Quaternion array interface
as_array = [ 0.94955541  0.16849094 -0.05885678  0.2578589 ]
from_array = Quaternion(w=0.949555, x=0.168491, y=-0.0588568, z=0.257859)




In [4]:


q = euler_to_quat(
    roll=np.deg2rad(20),
    pitch=np.deg2rad(-10),
    yaw=np.deg2rad(45)
)

fig  = plot_attitude(q, title="Single Attitude (Euler input)")


In [12]:


q = Quaternion(
    w=1,
    x=3,
    y=2.02,
    z=0.67
)

fig = plot_attitude(q, title="Single Attitude (Quaternion input)")
